# Generated by Django 4.1.8 on 2023-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_pornostar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Velit excepteur officia esse magna id dolor sint sunt eiusmod exercitation anim elit excepteur ut sint est est adipiscing ullamco do officia lorem pariatur elit officia nisi nulla adipiscing do velit proident id quis et veniam eu sit ea reprehenderit magna mollit sed fugiat fugiat commodo laborum irure eiusmod esse occaecat ex proident reprehenderit id ea voluptate voluptate cillum commodo nostrud adipiscing velit magna aliquip est aliqua sit dolor ipsum exercitation dolor dolor lorem irure ullamco culpa esse pariatur adipiscing cillum enim proident magna nulla ea adipiscing in laboris mollit in ullamco eiusmod et ex sit consequat nostrud fugiat reprehenderit'),
        ),
    ]
