# Generated by Django 4.1.8 on 2023-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_pornostar_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Nisi aliquip nulla id laboris ut aute eiusmod in enim consequat ea cillum culpa ad lorem sit pariatur veniam dolore ea commodo sed incididunt incididunt sint sunt exercitation proident dolore consectetur sint mollit sint laboris labore non do deserunt aliqua in ut esse nostrud dolore nostrud proident qui excepteur labore consectetur id sit consectetur cillum qui pariatur velit elit enim consequat nisi nisi aliqua ut ea reprehenderit ullamco reprehenderit ex culpa ea id mollit id est ex laboris officia quis sed consectetur lorem cupidatat mollit lorem elit eiusmod sint cillum nostrud officia dolor nostrud sint nostrud laborum mollit nisi dolore'),
        ),
    ]
