# Generated by Django 4.1.8 on 2023-05-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_pornostar_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Esse sed dolor aliquip non occaecat eiusmod sunt sint amet laborum culpa laborum est officia quis sint esse cillum aute commodo ullamco ea do et est dolor irure sunt id laborum labore do occaecat nulla aliquip sunt non amet aliqua labore officia amet quis nisi eiusmod eu exercitation reprehenderit occaecat lorem duis occaecat et nostrud dolore duis quis ipsum pariatur fugiat adipiscing lorem ut sint tempor consequat eiusmod ex qui et in quis ut sunt esse sint irure ut minim non reprehenderit esse velit esse occaecat pariatur ex irure et qui anim nisi duis proident cillum minim proident pariatur culpa'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('FX', 'Fixing'), ('PB', 'Publish')], default='PB', max_length=2)),
                ('comment_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.commentuser')),
                ('pornostar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.pornostar')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='blog_commen_created_0e6ed4_idx'),
        ),
    ]
