# Generated by Django 4.1.8 on 2023-05-09 07:47

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0006_commentuser_alter_pornostar_content_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pornostar',
            options={'ordering': ['-publish'], 'verbose_name': 'Pornostar', 'verbose_name_plural': 'Pornostars'},
        ),
        migrations.AddField(
            model_name='pornostar',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Proident pariatur labore velit irure dolor in cupidatat commodo sint ad amet enim velit minim labore excepteur tempor ut aliquip sunt cillum anim do veniam eiusmod laboris est officia nostrud proident aliquip pariatur cupidatat dolor do eu consectetur velit reprehenderit aute excepteur officia ea et ad commodo quis duis sint ad cupidatat ipsum ex labore cillum esse officia in duis consectetur velit minim eiusmod laborum excepteur ullamco minim excepteur nulla labore et ullamco aute sunt sunt eiusmod eiusmod veniam reprehenderit est sed magna ullamco voluptate aute in ex qui et aliqua mollit et pariatur magna pariatur enim incididunt velit sint'),
        ),
    ]
