# Generated by Django 4.1.8 on 2023-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_pornostar_options_pornostar_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Eiusmod adipiscing sint do ex do ad laborum in in nostrud voluptate ea eiusmod amet non irure in sunt dolore deserunt veniam amet nisi eiusmod pariatur non deserunt mollit sed non elit ullamco duis duis qui in commodo minim aliqua elit deserunt tempor voluptate lorem pariatur esse consequat ad sit aliquip ea tempor dolor magna eu est quis excepteur ex esse reprehenderit labore magna duis excepteur ullamco aute ad est adipiscing do ipsum minim veniam qui nulla officia nostrud minim labore irure commodo lorem sed labore incididunt laboris sint deserunt cupidatat officia mollit deserunt officia occaecat amet quis laboris reprehenderit'),
        ),
    ]
