# Generated by Django 4.1.8 on 2023-05-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_pornostar_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Deserunt consectetur mollit sit proident non ex quis commodo aliquip veniam officia commodo velit lorem nisi cupidatat lorem labore consequat ad est id ex ad et ullamco ea irure voluptate anim non quis reprehenderit sunt elit minim fugiat eu do dolore deserunt enim aute nostrud elit ipsum enim voluptate cillum voluptate dolor dolore sint in ut deserunt aute cillum consequat ad pariatur deserunt cupidatat id do dolore elit cillum ipsum anim aliquip voluptate et ullamco id nisi anim eiusmod reprehenderit nostrud ullamco in deserunt elit velit duis do nulla sint magna laboris elit minim sint velit elit laboris nulla sed'),
        ),
        migrations.AlterField(
            model_name='pornostar',
            name='slug',
            field=models.SlugField(unique_for_date='publish'),
        ),
    ]
