# Generated by Django 4.1.8 on 2023-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_pornostar_content_alter_pornostar_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_created_0e6ed4_idx',
        ),
        migrations.AlterField(
            model_name='pornostar',
            name='content',
            field=models.TextField(default='Magna irure amet dolor cupidatat officia irure non minim ad irure mollit duis pariatur eiusmod quis est duis do cupidatat ullamco amet sit ex amet et esse non anim tempor non ad in cupidatat sit commodo minim do sit et ad ipsum cillum sunt in lorem labore lorem veniam enim do in incididunt proident commodo do ut qui sit elit nulla proident duis sunt minim ullamco occaecat incididunt lorem aliquip consectetur aliqua ut eu consectetur ipsum amet minim sint dolore dolore duis consequat magna est do magna sint aute culpa dolor consectetur consectetur officia exercitation cupidatat nisi esse ea in'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='blog_commen_created_79f39f_idx'),
        ),
    ]
